name: Set up virtual environment and install packages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set up virtual environment
      run: |
        python3 -m venv .venv
        source .venv/bin/activate

    - name: Install packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save virtual environment
      run: |
        pip freeze > .venv/requirements.txt
        git add .venv/
